<?php

require __DIR__ . '/vendor/autoload.php';

use App\Kernel;
use App\Entity\Membre;
use Symfony\Component\Dotenv\Dotenv;

(new Dotenv())->bootEnv(__DIR__ . '/.env');

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();

$container = $kernel->getContainer();
$entityManager = $container->get('doctrine')->getManager();

$user = $entityManager->getRepository(Membre::class)->findOneBy(['username' => 'admin']);

if (!$user) {
    echo "User 'admin' not found in database.\n";
    exit(1);
}

echo "User 'admin' found.\n";
echo "Stored Hash: " . $user->getPassword() . "\n";

$passwordToVerify = 'admin';
if (password_verify($passwordToVerify, $user->getPassword())) {
    echo "Password '$passwordToVerify' is VALID.\n";
} else {
    echo "Password '$passwordToVerify' is INVALID.\n";
    
    // Let's try to generate a new hash using the container's hasher to see what it expects
    $hasherFactory = $container->get('security.password_hasher_factory');
    $passwordHasher = $hasherFactory->getPasswordHasher($user);
    $newHash = $passwordHasher->hash($passwordToVerify);
    echo "Expected Hash format (generated by Symfony): " . $newHash . "\n";
}
